import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { saveAs } from "file-saver";
import { BRAND } from "./brand";

export interface ReadingData {
  type: "palm" | "numerology" | "astrology";
  userInfo: {
    name: string;
    date: string;
    email?: string;
  };
  results: any;
  overallScore?: number;
  timestamp: string;
}

export interface ShareOptions {
  title: string;
  text: string;
  url?: string;
  files?: File[];
}

/**
 * Check if Web Share API is supported
 */
export const isWebShareSupported = (): boolean => {
  return typeof navigator !== "undefined" && "share" in navigator;
};

/**
 * Check if Web Share API supports files
 */
export const isWebShareFilesSupported = (): boolean => {
  return (
    isWebShareSupported() &&
    "canShare" in navigator &&
    navigator.canShare({ files: [] })
  );
};

/**
 * Generate PDF report from reading data
 */
export const generatePDFReport = async (
  readingData: ReadingData,
  elementId?: string,
): Promise<Blob> => {
  const pdf = new jsPDF("p", "mm", "a4");
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  // Set document properties
  pdf.setProperties({
    title: `${readingData.type.charAt(0).toUpperCase() + readingData.type.slice(1)} Reading Report`,
    subject: `Personal ${readingData.type} analysis`,
    author: "AI Cosmic Astro",
    creator: "AI Cosmic Astro Platform",
  });

  // Header with logo and branding
  pdf.setFillColor(139, 92, 246); // Purple color
  pdf.rect(0, 0, pageWidth, 25, "F");

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.setFont("helvetica", "bold");
  pdf.text("AI Cosmic Astro", 15, 17);

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.text(
    `${readingData.type.charAt(0).toUpperCase() + readingData.type.slice(1)} Reading Report`,
    pageWidth - 15,
    17,
    { align: "right" },
  );

  // User information section
  let yPosition = 40;

  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Personal Information", 15, yPosition);

  yPosition += 10;
  pdf.setFontSize(11);
  pdf.setFont("helvetica", "normal");
  pdf.text(`Name: ${readingData.userInfo.name}`, 15, yPosition);

  yPosition += 6;
  pdf.text(`Date: ${readingData.userInfo.date}`, 15, yPosition);

  yPosition += 6;
  pdf.text(
    `Report Generated: ${new Date(readingData.timestamp).toLocaleString()}`,
    15,
    yPosition,
  );

  yPosition += 15;

  // Overall score if available
  if (readingData.overallScore) {
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Overall Score", 15, yPosition);

    yPosition += 10;
    pdf.setFontSize(24);
    pdf.setTextColor(139, 92, 246);
    pdf.text(`${readingData.overallScore}%`, 15, yPosition);

    yPosition += 15;
    pdf.setTextColor(0, 0, 0);
  }

  // Report content based on type
  switch (readingData.type) {
    case "palm":
      yPosition = await addPalmAnalysisContent(
        pdf,
        readingData.results,
        yPosition,
        pageWidth,
        pageHeight,
      );
      break;
    case "numerology":
      yPosition = await addNumerologyContent(
        pdf,
        readingData.results,
        yPosition,
        pageWidth,
        pageHeight,
      );
      break;
    case "astrology":
      yPosition = await addAstrologyContent(
        pdf,
        readingData.results,
        yPosition,
        pageWidth,
        pageHeight,
      );
      break;
  }

  // Footer
  const footerY = pageHeight - 15;
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text(
    "Generated by AI-Powered Mystical Insights",
    pageWidth / 2,
    footerY,
    { align: "center" },
  );
  pdf.text(
    "© 2026 AI Cosmic Astro. All rights reserved.",
    pageWidth / 2,
    footerY + 5,
    { align: "center" },
  );

  return pdf.output("blob");
};

/**
 * Add palm analysis content to PDF
 */
const addPalmAnalysisContent = async (
  pdf: jsPDF,
  results: any,
  yPosition: number,
  pageWidth: number,
  pageHeight: number,
): Promise<number> => {
  const addNewPageIfNeeded = (requiredSpace: number): number => {
    if (yPosition + requiredSpace > pageHeight - 30) {
      pdf.addPage();
      return 30;
    }
    return yPosition;
  };

  // Guard against missing results
  if (!results) {
    return yPosition;
  }

  // Palm Lines Analysis
  yPosition = addNewPageIfNeeded(60);

  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Palm Lines Analysis", 15, yPosition);
  yPosition += 15;

  if (results.lines) {
    Object.entries(results.lines).forEach(([lineKey, line]: [string, any]) => {
      yPosition = addNewPageIfNeeded(30);

      const prettyName =
        lineKey === "lifeLine"
          ? "Life Line"
          : lineKey === "heartLine"
            ? "Heart Line"
            : lineKey === "headLine"
              ? "Head Line"
              : lineKey === "fateLine"
                ? "Fate Line"
                : `${lineKey} Line`;

      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text(prettyName, 15, yPosition);

      yPosition += 8;
      pdf.setFont("helvetica", "normal");
      pdf.text(`Quality: ${line.quality}`, 20, yPosition);

      yPosition += 6;
      pdf.text(`Score: ${line.score}%`, 20, yPosition);

      yPosition += 6;
      const splitMeaning = pdf.splitTextToSize(line.meaning, pageWidth - 30);
      pdf.text(splitMeaning, 20, yPosition);
      yPosition += splitMeaning.length * 4 + 3;

      if (line.details) {
        const splitDetails = pdf.splitTextToSize(
          `Details: ${line.details}`,
          pageWidth - 30,
        );
        pdf.text(splitDetails, 20, yPosition);
        yPosition += splitDetails.length * 4 + 5;
      }
    });
  }

  // Personality Traits & Physical Characteristics
  if (results.personality) {
    yPosition = addNewPageIfNeeded(50);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Personality & Hand Profile", 15, yPosition);
    yPosition += 12;

    // Physical characteristics
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text("Physical Characteristics", 15, yPosition);
    yPosition += 8;

    pdf.setFont("helvetica", "normal");
    const physLines = [
      `Dominant Hand: ${results.personality.dominantHand}`,
      `Palm Shape: ${results.personality.palmShape}`,
      `Finger Length: ${results.personality.fingerLength}`,
      `Hand Type: ${results.personality.handType}`,
    ];
    physLines.forEach((text) => {
      pdf.text(text, 20, yPosition);
      yPosition += 6;
    });

    // Personality traits with scores
    if (results.personality.traits?.length) {
      yPosition = addNewPageIfNeeded(20);
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Personality Traits", 15, yPosition);
      yPosition += 8;

      pdf.setFont("helvetica", "normal");
      results.personality.traits.forEach((trait: any) => {
        yPosition = addNewPageIfNeeded(16);
        pdf.text(
          `• ${trait.name} (${trait.score}%)`,
          20,
          yPosition,
        );
        yPosition += 6;
        const splitDesc = pdf.splitTextToSize(
          trait.description,
          pageWidth - 30,
        );
        pdf.text(splitDesc, 24, yPosition);
        yPosition += splitDesc.length * 4 + 3;
      });
    }
  }

  // Predictions
  if (results.predictions?.length) {
    yPosition = addNewPageIfNeeded(40);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Life Predictions", 15, yPosition);
    yPosition += 12;

    results.predictions.forEach((prediction: any) => {
      yPosition = addNewPageIfNeeded(30);
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text(
        `${prediction.area} (${prediction.timeframe})`,
        15,
        yPosition,
      );
      yPosition += 8;

      pdf.setFont("helvetica", "normal");
      const predText = pdf.splitTextToSize(
        `Prediction: ${prediction.prediction}`,
        pageWidth - 30,
      );
      pdf.text(predText, 20, yPosition);
      yPosition += predText.length * 4 + 3;

      const adviceText = pdf.splitTextToSize(
        `Advice: ${prediction.advice}`,
        pageWidth - 30,
      );
      pdf.text(adviceText, 20, yPosition);
      yPosition += adviceText.length * 4 + 3;

      pdf.text(`Confidence: ${prediction.confidence}%`, 20, yPosition);
      yPosition += 8;
    });
  }

  // Special Marks
  if (results.specialMarks?.length) {
    yPosition = addNewPageIfNeeded(30);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Special Marks & Symbols", 15, yPosition);
    yPosition += 12;

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    results.specialMarks.forEach((mark: any) => {
      yPosition = addNewPageIfNeeded(18);
      pdf.text(`• ${mark.name}`, 20, yPosition);
      yPosition += 6;
      const loc = mark.location ? `Location: ${mark.location}` : "";
      if (loc) {
        pdf.text(loc, 24, yPosition);
        yPosition += 6;
      }
      const meaning = pdf.splitTextToSize(
        `Meaning: ${mark.meaning}`,
        pageWidth - 30,
      );
      pdf.text(meaning, 24, yPosition);
      yPosition += meaning.length * 4 + 3;
      pdf.text(`Significance: ${mark.significance}`, 24, yPosition);
      yPosition += 6;
    });
  }

  // Compatibility
  if (results.compatibility?.length) {
    yPosition = addNewPageIfNeeded(30);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Compatibility with Other Hand Types", 15, yPosition);
    yPosition += 12;

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    results.compatibility.forEach((compat: any) => {
      yPosition = addNewPageIfNeeded(14);
      pdf.text(
        `• ${compat.type}: ${compat.match}% - ${compat.description}`,
        20,
        yPosition,
      );
      yPosition += 8;
    });
  }

  // Accuracy & Summary
  if (results.accuracy) {
    yPosition = addNewPageIfNeeded(30);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Analysis Confidence", 15, yPosition);
    yPosition += 12;

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    const metrics = [
      ["Line Detection", results.accuracy.lineDetection],
      ["Pattern Analysis", results.accuracy.patternAnalysis],
      ["Interpretation", results.accuracy.interpretation],
      ["Overall", results.accuracy.overall],
    ];
    metrics.forEach(([label, value]) => {
      if (typeof value === "number") {
        pdf.text(`${label}: ${value}%`, 20, yPosition);
        yPosition += 6;
      }
    });
  }

  if (results.summary) {
    yPosition = addNewPageIfNeeded(40);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Summary", 15, yPosition);
    yPosition += 12;

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    const summaryText = pdf.splitTextToSize(
      results.summary,
      pageWidth - 30,
    );
    pdf.text(summaryText, 20, yPosition);
    yPosition += summaryText.length * 4 + 5;
  }

  return yPosition;
};

/**
 * Add numerology content to PDF
 */
const addNumerologyContent = async (
  pdf: jsPDF,
  results: any,
  yPosition: number,
  pageWidth: number,
  pageHeight: number,
): Promise<number> => {
  const addNewPageIfNeeded = (requiredSpace: number): number => {
    if (yPosition + requiredSpace > pageHeight - 30) {
      pdf.addPage();
      return 30;
    }
    return yPosition;
  };

  // Core Numbers
  yPosition = addNewPageIfNeeded(60);

  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Your Core Numbers", 15, yPosition);
  yPosition += 15;

  const coreNumbers = [
    { label: "Life Path Number", value: results.life_path_number },
    { label: "Destiny Number", value: results.destiny_number },
    { label: "Soul Number", value: results.soul_number },
    { label: "Personality Number", value: results.personality_number },
  ];

  coreNumbers.forEach((number) => {
    if (number.value) {
      yPosition = addNewPageIfNeeded(8);
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "normal");
      pdf.text(`${number.label}: ${number.value}`, 20, yPosition);
      yPosition += 8;
    }
  });

  // Life Path Interpretation
  if (results.interpretation) {
    yPosition = addNewPageIfNeeded(40);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text(
      `Life Path ${results.life_path_number}: ${results.interpretation.title}`,
      15,
      yPosition,
    );
    yPosition += 15;

    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    const splitDescription = pdf.splitTextToSize(
      results.interpretation.description,
      pageWidth - 30,
    );
    pdf.text(splitDescription, 20, yPosition);
    yPosition += splitDescription.length * 4 + 10;

    // Traits
    if (results.interpretation.traits) {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Core Traits:", 20, yPosition);
      yPosition += 8;

      pdf.setFont("helvetica", "normal");
      const traitsText = results.interpretation.traits.join(", ");
      const splitTraits = pdf.splitTextToSize(traitsText, pageWidth - 30);
      pdf.text(splitTraits, 20, yPosition);
      yPosition += splitTraits.length * 4 + 10;
    }

    // Career guidance
    if (results.interpretation.career) {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Career Guidance:", 20, yPosition);
      yPosition += 8;

      pdf.setFont("helvetica", "normal");
      const splitCareer = pdf.splitTextToSize(
        results.interpretation.career,
        pageWidth - 30,
      );
      pdf.text(splitCareer, 20, yPosition);
      yPosition += splitCareer.length * 4 + 10;
    }
  }

  // Compatibility & Lucky Numbers
  if (results.compatibility || results.lucky_numbers) {
    yPosition = addNewPageIfNeeded(30);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Additional Insights", 15, yPosition);
    yPosition += 15;

    if (results.compatibility) {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Compatible Numbers:", 20, yPosition);
      yPosition += 8;

      pdf.setFont("helvetica", "normal");
      pdf.text(results.compatibility.join(", "), 20, yPosition);
      yPosition += 10;
    }

    if (results.lucky_numbers) {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text("Lucky Numbers:", 20, yPosition);
      yPosition += 8;

      pdf.setFont("helvetica", "normal");
      pdf.text(results.lucky_numbers.join(", "), 20, yPosition);
      yPosition += 10;
    }
  }

  return yPosition;
};

/**
 * Add astrology content to PDF
 */
const addAstrologyContent = async (
  pdf: jsPDF,
  results: any,
  yPosition: number,
  pageWidth: number,
  pageHeight: number,
): Promise<number> => {
  const addNewPageIfNeeded = (requiredSpace: number): number => {
    if (yPosition + requiredSpace > pageHeight - 30) {
      pdf.addPage();
      return 30;
    }
    return yPosition;
  };

  // Core Signs
  yPosition = addNewPageIfNeeded(60);

  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Your Astrological Profile", 15, yPosition);
  yPosition += 15;

  const coreSigns = [
    { label: "Sun Sign", value: results.sun_sign },
    { label: "Moon Sign", value: results.moon_sign },
    { label: "Rising Sign", value: results.rising_sign },
  ];

  coreSigns.forEach((sign) => {
    if (sign.value) {
      yPosition = addNewPageIfNeeded(8);
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "normal");
      pdf.text(`${sign.label}: ${sign.value}`, 20, yPosition);
      yPosition += 8;
    }
  });

  // Planetary positions
  if (results.planetary_positions) {
    yPosition = addNewPageIfNeeded(40);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Planetary Positions", 15, yPosition);
    yPosition += 15;

    Object.entries(results.planetary_positions).forEach(
      ([planet, sign]: [string, any]) => {
        yPosition = addNewPageIfNeeded(8);
        pdf.setFontSize(11);
        pdf.setFont("helvetica", "normal");
        pdf.text(`${planet}: ${sign}`, 20, yPosition);
        yPosition += 6;
      },
    );
  }

  // Daily forecast
  if (results.daily_forecast) {
    yPosition = addNewPageIfNeeded(40);

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Today's Forecast", 15, yPosition);
    yPosition += 15;

    Object.entries(results.daily_forecast).forEach(
      ([area, forecast]: [string, any]) => {
        yPosition = addNewPageIfNeeded(15);

        pdf.setFontSize(12);
        pdf.setFont("helvetica", "bold");
        pdf.text(
          `${area.charAt(0).toUpperCase() + area.slice(1)}:`,
          20,
          yPosition,
        );

        yPosition += 8;
        pdf.setFont("helvetica", "normal");
        const splitForecast = pdf.splitTextToSize(forecast, pageWidth - 30);
        pdf.text(splitForecast, 20, yPosition);
        yPosition += splitForecast.length * 4 + 5;
      },
    );
  }

  return yPosition;
};

/**
 * Download reading report as PDF
 */
export const downloadReport = async (
  readingData: ReadingData,
): Promise<void> => {
  try {
    const pdfBlob = await generatePDFReport(readingData);
    const fileName = `${readingData.type}-reading-${readingData.userInfo.name.replace(/\s+/g, "-")}-${new Date().toISOString().split("T")[0]}.pdf`;
    saveAs(pdfBlob, fileName);
  } catch (error) {
    console.error("Error generating PDF:", error);
    throw new Error("Failed to generate PDF report");
  }
};

/**
 * Share reading using Web Share API or fallback
 */
export const shareReading = async (
  readingData: ReadingData,
  options?: Partial<ShareOptions>,
): Promise<void> => {
  const defaultTitle = `My ${readingData.type.charAt(0).toUpperCase() + readingData.type.slice(1)} Reading`;
  const defaultText = `Check out my personalized ${readingData.type} reading from AI Cosmic Astro! ${readingData.overallScore ? `Overall score: ${readingData.overallScore}%` : ""}`;
  const defaultUrl = window.location.origin;

  const shareData: ShareOptions = {
    title: options?.title || defaultTitle,
    text: options?.text || defaultText,
    url: options?.url || defaultUrl,
    ...options,
  };

  // Try Web Share API first
  if (isWebShareSupported()) {
    try {
      // If files are provided and supported, include them
      if (options?.files && isWebShareFilesSupported()) {
        const canShareFiles = await navigator.canShare({
          files: options.files,
        });
        if (canShareFiles) {
          await navigator.share({
            title: shareData.title,
            text: shareData.text,
            files: options.files,
          });
          return;
        }
      }

      // Share without files
      await navigator.share({
        title: shareData.title,
        text: shareData.text,
        url: shareData.url,
      });
      return;
    } catch (error) {
      // If Web Share fails, fall back to other methods
      console.warn("Web Share API failed:", error);
    }
  }

  // Fallback to social media sharing
  await fallbackShare(shareData);
};

/**
 * Fallback sharing methods
 */
const fallbackShare = async (shareData: ShareOptions): Promise<void> => {
  const shareText = encodeURIComponent(`${shareData.text} ${shareData.url}`);
  const shareTitle = encodeURIComponent(shareData.title || "");
  const shareUrl = encodeURIComponent(shareData.url || "");

  // Create share menu
  const shareMenu = document.createElement("div");
  shareMenu.className =
    "fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4";
  shareMenu.innerHTML = `
    <div class="bg-white dark:bg-gray-800 rounded-lg p-6 max-w-sm w-full">
      <h3 class="text-lg font-semibold mb-4 text-gray-900 dark:text-gray-100">Share your reading</h3>
      <div class="grid grid-cols-2 gap-3">
        <button onclick="window.open('https://twitter.com/intent/tweet?text=${shareText}', '_blank')" 
                class="flex items-center justify-center gap-2 p-3 bg-teal-500 text-white rounded-lg hover:bg-teal-600 transition-colors">
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
            <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z"/>
          </svg>
          Twitter
        </button>
        
        <button onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=${shareUrl}&quote=${shareTitle}', '_blank')" 
                class="flex items-center justify-center gap-2 p-3 bg-teal-600 text-white rounded-lg hover:bg-teal-700 transition-colors">
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
            <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
          </svg>
          Facebook
        </button>
        
        <button onclick="window.open('https://www.linkedin.com/sharing/share-offsite/?url=${shareUrl}', '_blank')" 
                class="flex items-center justify-center gap-2 p-3 bg-teal-700 text-white rounded-lg hover:bg-teal-900 transition-colors">
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
            <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
          </svg>
          LinkedIn
        </button>
        
        <button onclick="navigator.clipboard.writeText('${shareData.text} ${shareData.url}').then(() => alert('Copied to clipboard!'))" 
                class="flex items-center justify-center gap-2 p-3 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"></path>
          </svg>
          Copy Link
        </button>
      </div>
      <button onclick="this.closest('.fixed').remove()" 
              class="mt-4 w-full p-2 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors">
        Cancel
      </button>
    </div>
  `;

  document.body.appendChild(shareMenu);

  // Close on backdrop click
  shareMenu.addEventListener("click", (e) => {
    if (e.target === shareMenu) {
      shareMenu.remove();
    }
  });
};

/**
 * Share reading with PDF report
 */
export const shareWithReport = async (
  readingData: ReadingData,
): Promise<void> => {
  try {
    const pdfBlob = await generatePDFReport(readingData);
    const fileName = `${readingData.type}-reading-${readingData.userInfo.name.replace(/\s+/g, "-")}.pdf`;
    const file = new File([pdfBlob], fileName, { type: "application/pdf" });

    await shareReading(readingData, {
      files: [file],
      text: `Check out my personalized ${readingData.type} reading report from AI Cosmic Astro!`,
    });
  } catch (error) {
    console.error("Error sharing with report:", error);
    // Fallback to sharing without file
    await shareReading(readingData);
  }
};

/**
 * Copy reading results to clipboard
 */
export const copyToClipboard = async (
  readingData: ReadingData,
): Promise<void> => {
  const text = generateTextSummary(readingData);

  try {
    await navigator.clipboard.writeText(text);
    return;
  } catch (error) {
    // Fallback for older browsers
    const textArea = document.createElement("textarea");
    textArea.value = text;
    document.body.appendChild(textArea);
    textArea.select();
    document.execCommand("copy");
    document.body.removeChild(textArea);
  }
};

/**
 * Generate text summary of reading
 */
const generateTextSummary = (readingData: ReadingData): string => {
  let summary = `My ${readingData.type.charAt(0).toUpperCase() + readingData.type.slice(1)} Reading from AI Cosmic Astro\n\n`;

  summary += `Name: ${readingData.userInfo.name}\n`;
  summary += `Date: ${readingData.userInfo.date}\n`;

  if (readingData.overallScore) {
    summary += `Overall Score: ${readingData.overallScore}%\n`;
  }

  summary += `\nGenerated on: ${new Date(readingData.timestamp).toLocaleString()}\n`;
  summary += `\nDiscover your destiny at ${BRAND.PRIMARY_DOMAIN}`;

  return summary;
};
